// src/renderer/shared/components/ui/text/Text.tsx
import { ParentProps, mergeProps } from 'solid-js';
import styles from './Text.module.css';

interface TextProps extends ParentProps {
  width?: string;
  padding?: string;
  whiteSpace?: string;
  overflow?: string;
  textOverflow?: string;
  size?: string;
  color?: string;
  disabledColor?: string;
  disabled?: boolean;
}

export function Text(props: TextProps) {
  const merged = mergeProps(
    {
      width: 'auto',
      padding: 'auto',
      whiteSpace: 'nowrap',
      overflow: 'auto',
      textOverflow: 'auto',
      size: 'auto',
      color: 'var(--text)',
      disabledColor: 'var(--text-disabled)',
      disabled: false,
    },
    props
  );

  const effectiveColor = () => (merged.disabled ? merged.disabledColor : merged.color);

  return (
    <span
      class={styles.text}
      style={{
        'font-size': merged.size,
        width: merged.width,
        color: effectiveColor(),
        padding: merged.padding,
        overflow: merged.overflow,
        'white-space': merged.whiteSpace,
        'text-overflow': merged.textOverflow,
      }}
    >
      {props.children}
    </span>
  );
}

// src/renderer/Common/Text/Text.svelte
<script lang="ts">
  export let width = "auto";
  export let padding = "auto";
  export let whiteSpace = "nowrap";
  export let overflow = "auto";
  export let textOverflow = "auto";
  export let size = "auto";
  export let color = "var(--text)";
  export let disabledColor = "var(--text-disabled)";

  export let disabled: boolean | undefined = false;

  if (typeof disabled === "boolean" && disabled) {
    color = disabledColor;
  }
</script>

<span
  style={`
    --size: ${size};
    --width: ${width};
    --color: ${color};
    --padding: ${padding};
    --overflow: ${overflow};
    --whiteSpace: ${whiteSpace};
    --textOverflow: ${textOverflow};
  `}
>
  <slot />
</span>

<style>
  span {
    color: var(--color);
    width: var(--width);
    padding: var(--padding);
    overflow: var(--overflow);
    white-space: var(--whiteSpace);
    text-overflow: var(--textOverflow);
    font-size: var(--size);
  }
</style>
