// src/renderer/Panel/Components/Tabs.svelte
<script lang="ts">
  import type { MouseWheelInputEvent } from "electron";
  import { tabs, currentTab } from "../store";
  import { closeTab, tabFocus } from "./utils";
  import List from "./List.svelte";
  import { NEW_FILE_TAB_TITLE } from "../../../constants/other";

  const api = window.panelAPI;

  let currentTabId = $state<number | undefined>(undefined);

  let item: HTMLDivElement;

  function wheelHandler(e: MouseWheelInputEvent) {
    if (e.deltaY > 0) {
      item.scrollLeft += 50;
    } else {
      item.scrollLeft -= 50;
    }
  }
  function dblclickHandler(e: MouseEvent) {
    api.windowMaximize();
    e.preventDefault();
    e.stopImmediatePropagation();
    e.stopPropagation();
  }

  function onClickTitle(event: MouseEvent, id: number) {
    switch (event.button) {
      // left mouse button
      case 0: {
        tabFocus(id);
        break;
      }
      // wheel mouse button
      case 1: {
        closeTab(id);
        break;
      }
      // right mouse button
      case 2: {
        api.openTabMenu(id, event.clientX, event.clientY);
        break;
      }
    }
  }

  function onClickClose(event: MouseEvent, id: number) {
    closeTab(id);
  }

  function onDndConsider(event: any) {
    tabs.set(event.detail.items);
  }
  function onDndFinalize(event: any) {
    const items = event.detail.items as Types.TabFront[];
    tabs.set(
      items
        .map((tab, index) => ({
          ...tab,
          order: tab.title === NEW_FILE_TAB_TITLE ? 0 : index + 1,
        }))
        .sort((a, b) => (a.order > b.order ? 1 : -1)),
    );
  }

  $effect(() => {
    const unsubscribe = currentTab.subscribe((id) => {
      if (typeof id === "number") {
        currentTabId = id;
      } else {
        currentTabId = undefined;
      }
    });
    return unsubscribe;
  });
</script>

<div class="panel-tabs" bind:this={item} onmousewheel={wheelHandler} ondblclick={dblclickHandler}>
  <List
    bind:items={$tabs}
    {currentTabId}
    {onClickTitle}
    {onClickClose}
    {onDndConsider}
    {onDndFinalize}
  />
</div>

<style>
  .panel-tabs {
    display: flex;
    flex-grow: 1;
    align-items: stretch;
    flex-flow: row;
    width: 100%;
    scrollbar-width: none;
    overflow-x: scroll;
    outline: none !important;
    color: var(--fg-tab) !important;
    -webkit-app-region: drag;
  }
  .panel-tabs:focus-visible {
    outline: none !important;
  }
  .panel-tabs::-webkit-scrollbar {
    display: none;
  }
</style>

// src/renderer/features/panel/components/Tabs.tsx
import { createSignal, createEffect } from 'solid-js';
import { tabsStore, currentTabStore } from '../stores';
import { closeTab, tabFocus } from './utils';
import { TabList } from './TabList';
import styles from './Tabs.module.css';

export function Tabs() {
  const api = window.panelAPI;
  let itemRef: HTMLDivElement | undefined;
  const [currentTabId, setCurrentTabId] = createSignal<number | undefined>(undefined);

  const wheelHandler = (e: WheelEvent) => {
    if (!itemRef) return;
    if (e.deltaY > 0) {
      itemRef.scrollLeft += 50;
    } else {
      itemRef.scrollLeft -= 50;
    }
  };

  const dblclickHandler = (e: MouseEvent) => {
    api.windowMaximize();
    e.preventDefault();
    e.stopImmediatePropagation();
    e.stopPropagation();
  };

  const onClickTitle = (event: MouseEvent, id: number) => {
    switch (event.button) {
      // left mouse button
      case 0: {
        tabFocus(id);
        break;
      }
      // wheel mouse button
      case 1: {
        closeTab(id);
        break;
      }
      // right mouse button
      case 2: {
        api.openTabMenu(id, event.clientX, event.clientY);
        break;
      }
    }
  };

  const onClickClose = (event: MouseEvent, id: number) => {
    closeTab(id);
  };

  const onReorder = (items: Types.TabFront[]) => {
    tabsStore.set(items);
  };

  createEffect(() => {
    const id = currentTabStore.get();
    if (typeof id === 'number') {
      setCurrentTabId(id);
    } else {
      setCurrentTabId(undefined);
    }
  });

  return (
    <div
      ref={itemRef}
      class={styles.panelTabs}
      onWheel={wheelHandler}
      onDblClick={dblclickHandler}
    >
      <TabList
        items={tabsStore.get()}
        currentTabId={currentTabId()}
        onClickTitle={onClickTitle}
        onClickClose={onClickClose}
        onReorder={onReorder}
      />
    </div>
  );
}
