// src/renderer/features/settings/components/views/theme-creator/ColorPalette.tsx
import { For, createSignal } from 'solid-js';
import { Flex } from 'Shared/components/ui/containers';
import { Text } from 'Shared/components/ui/text';
import { ColorPicker } from 'Shared/components/ui/inputs';
import { PALETTE_TEXT } from 'Const';
import { creatorThemeStore } from '../../../stores';
import styles from './ColorPalette.module.css';

export function ColorPalette() {
  const paletteKeys = () => Object.keys(creatorThemeStore.get().theme.palette);

  const handleColorChange = (key: string, value: string) => {
    creatorThemeStore.setColor(key, value);
  };

  return (
    <div class={styles.container}>
      <For each={paletteKeys()}>
        {(paletteKey) => (
          <>
            <Flex>
              <ColorPicker
                size={24}
                key={paletteKey}
                value={(creatorThemeStore.get().theme.palette as any)[paletteKey]}
                onValueChange={(value) => handleColorChange(paletteKey, value)}
              />
              <Flex width="10px" />
              <Text>{(PALETTE_TEXT as any)[paletteKey] ?? paletteKey}</Text>
            </Flex>
            <Flex height="6px" />
          </>
        )}
      </For>
    </div>
  );
}

// src/renderer/Settings/Components/Views/ThemeCreator/ColorPalette.svelte
<script lang="ts">
  import { Flex, Text, InputColor } from "Common";
  import { PALETTE_TEXT } from "Const";

  export let theme: Themes.Theme;

  const paletteKeys = Object.keys(theme.palette);
</script>

<div>
  {#each paletteKeys as key (key)}
    <Flex>
      <InputColor size={24} bind:value={theme.palette[key]} />
      <Flex width="10px" />
      <Text>{PALETTE_TEXT[key]}</Text>
    </Flex>
    <Flex height="6px" />
  {/each}
</div>
