// src/renderer/shared/components/ui/text/Line.tsx
import { ParentProps, mergeProps, createMemo } from 'solid-js';
import styles from './Line.module.css';

interface LineProps extends ParentProps {
  width?: string;
  height?: string;
  type?: 'H' | 'V';
}

export function Line(props: LineProps) {
  const merged = mergeProps(
    {
      width: undefined as string | undefined,
      height: undefined as string | undefined,
      type: 'H' as const,
    },
    props
  );

  const effectiveWidth = createMemo(() =>
    merged.type === 'H' ? (merged.width ?? '100%') : merged.width
  );
  const effectiveHeight = createMemo(() =>
    merged.type === 'V' ? (merged.height ?? '100%') : merged.height
  );

  return (
    <div
      class={styles.line}
      style={{
        '--width': effectiveWidth(),
        '--height': effectiveHeight(),
      }}
    >
      {props.children}
    </div>
  );
}

// src/renderer/Common/Other/Line.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface LineProps {
    width?: string;
    height?: string;
    type?: "H" | "V";
    children?: Snippet;
  }

  let {
    width = undefined,
    height = undefined,
    type = "H",
    children,
  }: LineProps = $props();

  let effectiveWidth = $derived(type === "H" ? (width ?? "100%") : width);
  let effectiveHeight = $derived(type === "V" ? (height ?? "100%") : height);
</script>

<div
  style={`
    --width: ${effectiveWidth};
    --height: ${effectiveHeight};
  `}
>
  {@render children?.()}
</div>

<style>
  div {
    border: 1px solid var(--borders);
    width: var(--width);
    height: var(--height);
  }
</style>
