// src/renderer/shared/components/ui/containers/Flex.tsx
import { ParentProps, mergeProps } from 'solid-js';
import styles from './Flex.module.css';

interface FlexProps extends ParentProps {
  width?: string;
  height?: string;
  padding?: string;
  margin?: string;
  direction?: 'row' | 'column';
  justifyContent?: string;
  overflow?: string;
  justifyItems?: string;
  alignItems?: string;
  border?: string;
  borderTop?: string;
  borderRight?: string;
  borderBottom?: string;
  borderLeft?: string;
  borderRadius?: string;
  bgColor?: string;
}

export function Flex(props: FlexProps) {
  const merged = mergeProps(
    {
      width: 'auto',
      height: 'auto',
      padding: '0',
      margin: '0',
      direction: 'row' as const,
      justifyContent: 'auto',
      overflow: 'auto',
      justifyItems: 'auto',
      alignItems: 'auto',
      border: 'none',
      borderTop: 'none',
      borderRight: 'none',
      borderBottom: 'none',
      borderLeft: 'none',
      borderRadius: 'none',
      bgColor: 'transparent',
    },
    props
  );

  return (
    <div
      class={styles.flex}
      style={{
        '--width': merged.width,
        '--height': merged.height,
        '--direction': merged.direction,
        '--justifyItems': merged.justifyItems,
        '--justifyContent': merged.justifyContent,
        '--alignItems': merged.alignItems,
        '--overflow': merged.overflow,
        '--border': merged.border,
        '--tborder': merged.borderTop,
        '--rborder': merged.borderRight,
        '--bborder': merged.borderBottom,
        '--lborder': merged.borderLeft,
        '--bradius': merged.borderRadius,
        '--padding': merged.padding,
        '--margin': merged.margin,
        '--bgColor': merged.bgColor,
      }}
    >
      {props.children}
    </div>
  );
}

// src/renderer/Common/Containers/Flex.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface FlexProps {
    width?: string;
    height?: string;
    padding?: string;
    margin?: string;
    der?: "row" | "column";
    justifyContent?: string;
    overflow?: string;
    justifyItems?: string;
    alignItems?: string;
    border?: string;
    tborder?: string;
    rborder?: string;
    bborder?: string;
    lborder?: string;
    bradius?: string;
    bgColor?: string;
    children?: Snippet;
  }

  let {
    width = "auto",
    height = "auto",
    padding = "0",
    margin = "0",
    der = "row",
    justifyContent = "auto",
    overflow = "auto",
    justifyItems = "auto",
    alignItems = "auto",
    border = "none",
    tborder = "none",
    rborder = "none",
    bborder = "none",
    lborder = "none",
    bradius = "none",
    bgColor = "transparent",
    children,
  }: FlexProps = $props();
</script>

<div
  style={`
    --width: ${width};
    --height: ${height};
    --direction: ${der};
    --justifyItems: ${justifyItems};
    --justifyContent: ${justifyContent};
    --alignItems: ${alignItems};
    --overflow: ${overflow};
    --border: ${border};
    --tborder: ${tborder};
    --rborder: ${rborder};
    --bborder: ${bborder};
    --lborder: ${lborder};
    --bradius: ${bradius};
    --padding: ${padding};
    --margin: ${margin};
    --bgColor: ${bgColor};
  `}
>
  {@render children?.()}
</div>

<style>
  div {
    display: flex;
    flex-direction: var(--direction);
    justify-content: var(--justifyContent);
    justify-items: var(--justifyItems);
    overflow: var(--overflow);
    border: var(--border);
    border-top: var(--tborder);
    border-right: var(--rborder);
    border-bottom: var(--bborder);
    border-left: var(--lborder);
    border-radius: var(--bradius);
    align-items: var(--alignItems);
    width: var(--width);
    height: var(--height);
    padding: var(--padding);
    margin: var(--margin);
    background-color: var(--bgColor);
  }
</style>
