// src/renderer/shared/components/ui/containers/FlexItem.tsx
import { ParentProps, mergeProps } from 'solid-js';

interface FlexItemProps extends ParentProps {
  grow?: number;
  flex?: number;
}

export function FlexItem(props: FlexItemProps) {
  const merged = mergeProps({ grow: 0, flex: 0 }, props);

  return (
    <div
      style={{
        flex: merged.flex,
        'flex-grow': merged.grow,
      }}
    >
      {props.children}
    </div>
  );
}

// src/renderer/Common/Containers/FlexItem.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface FlexItemProps {
    grow?: number;
    flex?: number;
    children?: Snippet;
  }

  let { grow = 0, flex = 0, children }: FlexItemProps = $props();
</script>

<div
  style={`
    flex: ${flex};
    flex-grow: ${grow};
  `}
>
  {@render children?.()}
</div>
