// src/renderer/Settings/Components/Views/Themes/ThemeItem.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { getColorPallet } from "Utils/Render";

  import { Text, Label, Flex, FlexItem, Rotate } from "Common";
  import { PrimaryButton, ButtonTool } from "Common/Buttons";
  import {
    Burger,
    Hand,
    Component,
    Download,
    Pencil2,
    RadioNormal,
    RadioChecked,
  } from "Common/Icons";

  export let canEdit = false;
  export let currentThemeId: string;
  export let theme: Themes.Theme;

  let radio: ConstructorOfATypedSvelteComponent;
  $: radio = currentThemeId === theme.id ? RadioChecked : RadioNormal;

  const dispatch = createEventDispatcher();
</script>

<div>
  <div
    class="themeview_item_tumbl"
    on:mouseup={() => dispatch("applyTheme", { themeId: theme.id })}
    style={getColorPallet(theme).join(";")}
  >
    <div class="themeview_item_tumbl_top" />
    <div class="themeview_item_tumbl_toolpanel">
      <div>
        <Burger color="var(--text)" />
        <Hand color="var(--text)" />
      </div>
      <div>
        <Component color="var(--textComponent)" />
      </div>
      <div>
        <PrimaryButton width="30px" height="16px" padding="0" />
      </div>
    </div>
    <div class="themeview_item_tumbl_body">
      <div class="themeview_item_tumbl_body_left">
        <div class="themeview_item_tumbl_body_left_text1" />
        <div class="themeview_item_tumbl_body_left_text2" />
      </div>
      <div class="themeview_item_tumbl_body_center" />
      <div class="themeview_item_tumbl_body_right" />
    </div>
  </div>
  <Flex
    padding="14px"
    lborder="1px solid var(--borders)"
    rborder="1px solid var(--borders)"
    bborder="1px solid var(--borders)"
    bradius="0 0 6px 6px"
  >
    <FlexItem grow={2}>
      <Flex der="column">
        <Label padding="0">{theme.name}</Label>
        <Text whiteSpace="wrap">{theme.author}</Text>
      </Flex>
    </FlexItem>
    <FlexItem grow={1}>
      <Flex alignItems="center" justifyContent="end" height="100%">
        {#if canEdit}
          <ButtonTool
            normalBgColor="tarsparent"
            on:mouseup={() => dispatch("editTheme", { themeId: theme.id })}
          >
            <Pencil2 color="var(--text)" size="16" />
          </ButtonTool>
        {/if}
        <Flex width="10px" />
        <ButtonTool
          normalBgColor="tarsparent"
          on:mouseup={() => dispatch("useColorPalette", { themeId: theme.id })}
        >
          <Rotate deg={-90}>
            <Download color="var(--text)" size="16" />
          </Rotate>
        </ButtonTool>
        <Flex width="10px" />
        <ButtonTool
          normalBgColor="tarsparent"
          on:mouseup={() => dispatch("applyTheme", { themeId: theme.id })}
        >
          <svelte:component this={radio} color="var(--text)" />
        </ButtonTool>
      </Flex>
    </FlexItem>
  </Flex>
</div>

<style>
  .themeview_item_tumbl {
    flex-direction: column;
    height: 159px;
    border: 1px solid var(--borders);
    border-radius: 6px 6px 0 0;
  }
  .themeview_item_tumbl:hover {
    cursor: pointer;
  }
  .themeview_item_tumbl_top {
    height: 8px;
    background-color: var(--bg-header);
    border-radius: 6px 6px 0 0;
  }
  .themeview_item_tumbl_toolpanel {
    display: grid;
    grid-template-columns: 60px 1fr 60px;
    height: 24px;
    align-items: center;
    background-color: var(--bg-toolbar);
  }
  .themeview_item_tumbl_toolpanel > div {
    display: flex;
    align-items: flex-end;
  }
  .themeview_item_tumbl_toolpanel > div:nth-child(1) {
    padding-left: 6px;
  }
  .themeview_item_tumbl_toolpanel > div:nth-child(2) {
    justify-content: center;
  }
  .themeview_item_tumbl_body {
    display: grid;
    grid-template-columns: 60px 1fr 60px;
    height: 127px;
  }
  .themeview_item_tumbl_body_left {
    padding-left: 8px;
    padding-top: 10px;
    background-color: var(--bg-panel);
    border-right: 1px solid var(--borders);
  }
  .themeview_item_tumbl_body_left_text1 {
    width: 40px;
    height: 4px;
    background-color: var(--text);
  }
  .themeview_item_tumbl_body_left_text2 {
    margin-top: 6px;
    width: 28px;
    height: 4px;
    background-color: var(--text);
  }
  .themeview_item_tumbl_body_center {
    background-color: var(--borders);
  }
  .themeview_item_tumbl_body_right {
    border-left: 1px solid var(--borders);
    background-color: var(--bg-panel);
  }
</style>

// src/renderer/features/settings/components/views/themes/ThemeItem.tsx
import { createMemo, Show } from 'solid-js';
import { getColorPallet } from 'Utils/Render';
import { Text, Label } from 'Shared/components/ui/text';
import { Flex, FlexItem, Rotate } from 'Shared/components/ui/containers';
import { PrimaryButton, ButtonTool } from 'Shared/components/ui/buttons';
import {
  Burger,
  Hand,
  Component,
  Download,
  Pencil2,
  RadioNormal,
  RadioChecked,
  Delete,
} from 'Shared/components/icons';
import styles from './ThemeItem.module.css';

interface ThemeItemProps {
  canEdit?: boolean;
  canDelete?: boolean;
  currentThemeId?: string;
  theme: Themes.Theme;
  onApplyTheme?: () => void;
  onDeleteTheme?: () => void;
  onEditTheme?: () => void;
  onUseColorPalette?: () => void;
}

export function ThemeItem(props: ThemeItemProps) {
  const isSelected = createMemo(() => props.currentThemeId === props.theme.id);
  const paletteStyle = createMemo(() => getColorPallet(props.theme).join(';'));

  return (
    <div>
      <div
        class={styles.themeviewItemTumbl}
        onMouseUp={props.onApplyTheme}
        style={paletteStyle()}
      >
        <div class={styles.themeviewItemTumblTop} />
        <div class={styles.themeviewItemTumblToolpanel}>
          <div>
            <Burger color="var(--text)" />
            <Hand color="var(--text)" />
          </div>
          <div>
            <Component color="var(--textComponent)" />
          </div>
          <div>
            <PrimaryButton width="30px" height="16px" padding="0" />
          </div>
        </div>
        <div class={styles.themeviewItemTumblBody}>
          <div class={styles.themeviewItemTumblBodyLeft}>
            <div class={styles.themeviewItemTumblBodyLeftText1} />
            <div class={styles.themeviewItemTumblBodyLeftText2} />
          </div>
          <div class={styles.themeviewItemTumblBodyCenter} />
          <div class={styles.themeviewItemTumblBodyRight} />
        </div>
      </div>
      <Flex
        padding="14px"
        borderLeft="1px solid var(--borders)"
        borderRight="1px solid var(--borders)"
        borderBottom="1px solid var(--borders)"
        borderRadius="0 0 6px 6px"
      >
        <FlexItem grow={2}>
          <Flex direction="column">
            <Label padding="0">{props.theme.name}</Label>
            <Text>{props.theme.author}</Text>
          </Flex>
        </FlexItem>
        <FlexItem grow={1}>
          <Flex alignItems="center" justifyContent="end" height="100%">
            <Show when={props.canEdit}>
              <ButtonTool normalBgColor="transparent" onClick={props.onEditTheme}>
                <Pencil2 color="var(--text)" size="16" />
              </ButtonTool>
            </Show>
            <Flex width="10px" />
            <ButtonTool normalBgColor="transparent" onClick={props.onUseColorPalette}>
              <Rotate deg={-90}>
                <Download color="var(--text)" size="16" />
              </Rotate>
            </ButtonTool>
            <Flex width="10px" />
            <ButtonTool normalBgColor="transparent" onClick={props.onApplyTheme}>
              {isSelected() ? (
                <RadioChecked color="var(--text)" />
              ) : (
                <RadioNormal color="var(--text)" />
              )}
            </ButtonTool>
            <Show when={props.canDelete}>
              <Flex width="20px" />
              <ButtonTool normalBgColor="transparent" onClick={props.onDeleteTheme}>
                <Delete color="var(--text)" size="18" />
              </ButtonTool>
            </Show>
          </Flex>
        </FlexItem>
      </Flex>
    </div>
  );
}
