// src/renderer/components/Settings/views/General/index.tsx
import * as React from "react";
import { observer, inject } from "mobx-react";

import "./index.css";
import { Input, List, CheckBox, Text, Button, Icon } from "Elements";
import { Settings } from "Store/Settings";
import ListItems from "./listItems";

interface GeneralBodyProps {
  settings?: Settings;
}

const GeneralBody: React.FunctionComponent<GeneralBodyProps> = props => {
  return (
    <div className="general">
      <div className="section grid grid_1x3">
        <div>
          <Text type="subtitle">Scale UI</Text>
          <Input
            readonlyInput
            value={Math.round(props.settings.settings.ui.scaleFigmaUI * 100)}
            type="range"
            className="justify__content_center"
            displayValue
            suffix="%"
            min={50}
            max={150}
            step={5}
            onChange={(e, d) => props.settings.updateFigmaUiScale(d)}
          />
        </div>
        <div></div>
        <div>
          <Text type="subtitle">Scale Tabs</Text>
          <Input
            readonlyInput
            value={Math.round(props.settings.settings.ui.scalePanel * 100)}
            type="range"
            className="justify__content_center"
            displayValue
            suffix="%"
            min={50}
            max={150}
            step={5}
            onChange={(e, d) => props.settings.updatePanelScale(d)}
          />
        </div>
      </div>
      <div className="section grid grid_1x3">
        <div>
          <Text type="subtitle">Main settings</Text>
          <CheckBox
            value={props.settings.settings.app.saveLastOpenedTabs}
            text="Save the last opened tabs"
            onChange={props.settings.saveLastOpenedTabs}
          />
          <CheckBox
            value={props.settings.settings.app.enableColorSpaceSrgb}
            text="Enable color space sRGB"
            onChange={props.settings.enableColorSpaceSrgb}
          />
          <CheckBox
            value={props.settings.settings.app.visibleNewProjectBtn}
            text="Show new project button"
            onChange={props.settings.visibleNewProjectBtn}
          />
          <CheckBox
            value={props.settings.settings.app.useZenity}
            text="Use Zenity for Dialogs"
            onChange={props.settings.changeUseZenity}
          />
        </div>
        <div></div>
        <div className="flex flex_column">
          <Text type="subtitle">Export files to</Text>
          <div className="flex align_items_center">
            <Input
              type="text"
              className="justify__content_left flex_grow_1 input_inline border_light input_w_70per marg_right_10px"
              contentBefore={
                <Button
                  className="button_clear"
                  onClick={(): void => {
                    props.settings.selectExportDir();
                  }}
                >
                  <Icon color="var(--text)" size="22" type="Folder" />
                </Button>
              }
              value={props.settings.settings.app.exportDir}
              onChange={(e): void => props.settings.inputExportDir(e.target.value)}
            />
            <Button
              text="Change"
              type="primary"
              className="width_60px"
              onClick={(): void => {
                props.settings.selectExportDir();
              }}
            />
          </div>
        </div>
      </div>
      <div className="section section_end grid grid_1x3">
        <div>
          <Text type="subtitle">Font directories</Text>
          <div className="flex flex_column border_light pad_left_10px pad_top_10px">
            <Button
              type="primary"
              text="+ Add directory"
              className="width_120px"
              onClick={(): void => {
                props.settings.addDir();
              }}
            />
            <List>
              <ListItems items={props.settings.settings.app.fontDirs} onRemove={props.settings.removeDir} />
            </List>
          </div>
        </div>
        <div></div>
        <div>
          {/* <Text type="subtitle">
            UI font
          </Text>
          <ComboBox className="border_light" items={["Inter", "Huinter", "Times New Roman", "Font Hueta"]} /> */}
        </div>
      </div>
    </div>
  );
};

export default inject("settings")(observer(GeneralBody));

// src/renderer/Settings/Components/Views/General/index.svelte
<script lang="ts">
  import { ipcRenderer } from "electron";
  import { InputRange, CheckBox, InputText, ListBox } from "Common/Input";
  import { Text, Label, Flex, FlexItem, Line } from "Common";
  import { ButtonTool, SecondaryButton } from "Common/Buttons";
  import { TOPPANELHEIGHT } from "Const";
  import { Folder } from "Common/Icons";
  import { settings } from "../../../store";

  import DirectoryListItem from "./DirectoryListItem.svelte";

  let items: Types.TabItem[] = [];
  $: items = $settings.app.fontDirs.map((dir) => ({
    id: dir,
    text: dir,
    item: DirectoryListItem,
  }));

  async function onChangeExportPath(event: MouseEvent) {
    const directory = await ipcRenderer.invoke("selectExportDirectory");

    if (!directory) {
      return;
    }

    $settings.app.exportDir = directory;
  }
  function onItemRemoveClick(item: Types.TabItem) {
    $settings.app.fontDirs = items.filter((dir) => dir.id !== item.id).map((item) => item.id);
  }
  async function onAddDirectory(event: MouseEvent) {
    const directory = await ipcRenderer.invoke("selectExportDirectory");

    if (!directory) {
      return;
    }

    $settings.app.fontDirs.push(directory);
    $settings.app.fontDirs = $settings.app.fontDirs;
  }
  function onClearList(event: MouseEvent) {
    $settings.app.fontDirs = [];
  }

  $: {
    ipcRenderer.invoke("updateFigmaUiScale", $settings.ui.scaleFigmaUI);
  }
  $: {
    ipcRenderer.invoke("updatePanelScale", $settings.ui.scalePanel);
    $settings.app.panelHeight = Math.floor(TOPPANELHEIGHT * $settings.ui.scalePanel);
  }
</script>

<div>
  <Flex>
    <Flex der="column" width="-webkit-fill-available">
      <Label>Scale UI</Label>
      <InputRange bind:value={$settings.ui.scaleFigmaUI} min={0.5} max={1.5} step={0.05} />
      <Flex der="column" alignItems="center" justifyContent="center">
        <Text padding="8px 0 0 0">{Math.floor($settings.ui.scaleFigmaUI * 100)}%</Text>
      </Flex>
    </Flex>
    <Flex width="120px" />
    <Flex der="column" width="-webkit-fill-available">
      <Label>Scale Tabs</Label>
      <InputRange bind:value={$settings.ui.scalePanel} min={0.5} max={1.5} step={0.05} />
      <Flex der="column" alignItems="center" justifyContent="center">
        <Text padding="8px 0 0 0">{Math.floor($settings.ui.scalePanel * 100)}%</Text>
      </Flex>
    </Flex>
  </Flex>

  <Flex height="50px" />
  <Line />
  <Flex height="40px" />

  <Flex>
    <Flex der="column" width="-webkit-fill-available">
      <Label>Main settings</Label>
      <CheckBox bind:checked={$settings.app.saveLastOpenedTabs} text="Save the last opened tabs" />
      <CheckBox bind:checked={$settings.app.enableColorSpaceSrgb} text="Enable color space sRGB" />
      <CheckBox bind:checked={$settings.app.visibleNewProjectBtn} text="Show new project button" />
      <CheckBox bind:checked={$settings.app.useZenity} text="Use Zenity for Dialogs" />
      <CheckBox bind:checked={$settings.app.disableThemes} text="Disable themes" />
    </Flex>
    <Flex width="120px" />
    <Flex der="column" width="-webkit-fill-available">
      <Label>Export files to</Label>
      <Flex>
        <FlexItem grow={1}>
          <InputText bind:value={$settings.app.exportDir}>
            <ButtonTool normalBgColor="tarsparent" on:mouseup={onChangeExportPath}>
              <Folder color="var(--text)" size="18" />
            </ButtonTool>
          </InputText>
        </FlexItem>
        <Flex width="20px" />
        <SecondaryButton on:mouseup={onChangeExportPath}>Change</SecondaryButton>
      </Flex>
    </Flex>
  </Flex>

  <Flex height="50px" />
  <Line />
  <Flex height="40px" />

  <Flex>
    <Flex der="column" width="-webkit-fill-available">
      <Label>Font directories</Label>
      <ListBox {items} {onItemRemoveClick} height="160px" />
      <Flex height="10px" />
      <Flex>
        <FlexItem grow={1} />
        <SecondaryButton on:mouseup={onClearList}>Clear list</SecondaryButton>
        <Flex width="10px" />
        <SecondaryButton on:mouseup={onAddDirectory}>Add directory</SecondaryButton>
      </Flex>
    </Flex>
    <!-- <Flex width="120px" /> -->
    <!-- <Flex der="column" width="-webkit-fill-available"> -->
    <!-- TODO: -->
    <!-- <Label>UI font</Label> -->
    <!-- <InputText bind:value={textValue} /> -->
    <!-- </Flex> -->
  </Flex>
</div>

<style>
  div {
    padding: 32px 32px 8px 32px;
  }
</style>
