// src/renderer/Common/Containers/DropDown.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { onMount } from "svelte";
  import { tweened } from "svelte/motion";
  import { cubicOut } from "svelte/easing";

  interface DropDownProps {
    title: string;
    isEmpty?: boolean;
    open?: boolean;
    duration?: number;
    children?: Snippet;
  }

  let {
    title,
    isEmpty = $bindable(false),
    open = $bindable(false),
    duration = 400,
    children,
  }: DropDownProps = $props();

  let height = $state(0);
  let content: HTMLDivElement;
  const bodyHeight = tweened(0, {
    duration,
    easing: cubicOut,
  });

  function calcHeight() {
    if (!content) {
      return;
    }

    const bounds = content.getBoundingClientRect();

    height = isEmpty ? 0 : bounds.height;

    if (open) {
      bodyHeight.set(height);
    }
  }

  function onChange(event: Event) {
    const elem = event.target as HTMLInputElement;

    calcHeight();

    if (elem.checked) {
      bodyHeight.set(height);
    } else {
      bodyHeight.set(0);
    }
  }

  onMount(calcHeight);

  $effect(() => {
    window.addEventListener("resize", calcHeight);
    return () => window.removeEventListener("resize", calcHeight);
  });
</script>

<div>
  <label>
    <input type="checkbox" bind:checked={open} onchange={onChange} onfocusin={onChange} />
    <span>{title}</span>
  </label>
  <block
    style={`
      height: ${$bodyHeight}px;
    `}
  >
    <blockContent bind:this={content}>
      {@render children?.()}
    </blockContent>
  </block>
</div>

<style>
  div {
    width: 100%;
  }
  label {
    display: flex;
    align-items: center;
    width: 100%;
    user-select: none;
  }
  span {
    position: relative;
    width: 100%;
    border-bottom: 1px solid var(--borders);
    padding-left: 24px;
    color: var(--text);
  }

  blockContent {
    display: block;
  }
  block {
    display: block;
    width: 100%;
    overflow: hidden;
  }

  input {
    display: none;
  }
  input ~ span::before {
    content: "";
    position: absolute;
    top: 6px;
    left: 6px;
    width: 0;
    height: 0;
    border-top: 5px solid var(--borders);
    border-right: 5px solid transparent;
    border-left: 5px solid transparent;
    transform: rotate(-90deg);
    transition: all 0.1s ease;
  }
  input:checked ~ span::before {
    content: "";
    position: absolute;
    top: 6px;
    left: 6px;
    width: 0;
    height: 0;
    border-top: 5px solid var(--borders);
    border-right: 5px solid transparent;
    border-left: 5px solid transparent;
    transform: rotate(0deg);
    transition: all 0.1s ease;
  }
</style>

// src/renderer/shared/components/ui/containers/DropDown.tsx
import { ParentProps, createSignal, createEffect, onMount, onCleanup, mergeProps } from 'solid-js';
import styles from './DropDown.module.css';

interface DropDownProps extends ParentProps {
  title: string;
  isEmpty?: boolean;
  open?: boolean;
  duration?: number;
  onOpenChange?: (open: boolean) => void;
}

export function DropDown(props: DropDownProps) {
  const merged = mergeProps(
    {
      isEmpty: false,
      open: false,
      duration: 400,
    },
    props
  );

  let contentRef: HTMLDivElement | undefined;
  const [height, setHeight] = createSignal(0);
  const [bodyHeight, setBodyHeight] = createSignal(0);
  const [isOpen, setIsOpen] = createSignal(merged.open);

  const calcHeight = () => {
    if (!contentRef) return;

    const bounds = contentRef.getBoundingClientRect();
    const newHeight = merged.isEmpty ? 0 : bounds.height;
    setHeight(newHeight);

    if (isOpen()) {
      setBodyHeight(newHeight);
    }
  };

  const handleChange = (event: Event) => {
    const elem = event.target as HTMLInputElement;
    calcHeight();

    if (elem.checked) {
      setIsOpen(true);
      setBodyHeight(height());
    } else {
      setIsOpen(false);
      setBodyHeight(0);
    }

    props.onOpenChange?.(elem.checked);
  };

  onMount(() => {
    calcHeight();
    window.addEventListener('resize', calcHeight);
  });

  onCleanup(() => {
    window.removeEventListener('resize', calcHeight);
  });

  createEffect(() => {
    if (props.open !== undefined) {
      setIsOpen(props.open);
      if (props.open) {
        calcHeight();
        setBodyHeight(height());
      } else {
        setBodyHeight(0);
      }
    }
  });

  return (
    <div class={styles.container}>
      <label class={styles.label}>
        <input
          type="checkbox"
          class={styles.input}
          checked={isOpen()}
          onChange={handleChange}
          onFocusIn={handleChange}
        />
        <span class={`${styles.span} ${isOpen() ? styles.spanOpen : ''}`}>{props.title}</span>
      </label>
      <div
        class={styles.block}
        style={{
          height: `${bodyHeight()}px`,
          'transition-duration': `${merged.duration}ms`,
        }}
      >
        <div ref={contentRef} class={styles.blockContent}>
          {props.children}
        </div>
      </div>
    </div>
  );
}
