// src/renderer/Common/Containers/Rotate.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface RotateProps {
    deg?: number;
    children?: Snippet;
  }

  let { deg = 0, children }: RotateProps = $props();
</script>

<div
  style={`
    --deg: ${deg}deg;
  `}
>
  {@render children?.()}
</div>

<style>
  div {
    display: flex;
    transform: rotate(var(--deg));
  }
</style>

// src/renderer/shared/components/ui/containers/Rotate.tsx
import { ParentProps, mergeProps } from 'solid-js';
import styles from './Rotate.module.css';

interface RotateProps extends ParentProps {
  deg?: number;
}

export function Rotate(props: RotateProps) {
  const merged = mergeProps({ deg: 0 }, props);

  return (
    <div class={styles.rotate} style={{ '--deg': `${merged.deg}deg` }}>
      {props.children}
    </div>
  );
}
