// src/renderer/elements/Input/types/Range.tsx
import * as React from "react";

import "../index.css";

export interface InputRangeProps {
  onChange(event: React.MouseEvent<any> | React.ChangeEvent<any>, delta: number): void;
  value?: string | number;
  suffix?: string;
  displayLabel?: boolean;
  displayValue?: boolean;
  readonlyInput?: boolean;
  min?: number;
  max?: number;
  step?: number;
}

export const InputRange: React.FunctionComponent<InputRangeProps> = props => {
  return (
    <React.Fragment>
      <input
        className="input__range"
        readOnly={!!props.readonlyInput}
        type="range"
        min={props.min || 0}
        max={props.max || 100}
        step={props.step || 5}
        value={props.value ? props.value : ""}
        onChange={e => props.onChange(e, +e.target.value)}
      />
      {props.displayValue ? (
        <span className="input__label">
          {props.value}
          {props.suffix ? props.suffix : ""}
        </span>
      ) : (
        ""
      )}
    </React.Fragment>
  );
};

// src/renderer/shared/components/ui/inputs/Range.tsx
import { mergeProps } from 'solid-js';
import styles from './Range.module.css';

interface RangeProps {
  value?: number;
  readonly?: boolean;
  max?: number;
  min?: number;
  step?: number;
  width?: string;
  thumbSize?: string;
  trackSize?: string;
  onValueChange?: (value: number) => void;
  onChange?: (event: Event) => void;
}

export function Range(props: RangeProps) {
  const merged = mergeProps(
    {
      value: 0,
      readonly: false,
      max: 100,
      min: 0,
      step: 1,
      width: 'auto',
      thumbSize: '16px',
      trackSize: '2px',
    },
    props
  );

  const handleInput = (event: Event) => {
    const target = event.target as HTMLInputElement;
    props.onValueChange?.(Number(target.value));
  };

  const handleChange = (event: Event) => {
    props.onChange?.(event);
  };

  return (
    <input
      class={styles.range}
      style={{
        '--inputWidth': merged.width,
        '--thumbSize': merged.thumbSize,
        '--trackSize': merged.trackSize,
      }}
      type="range"
      readonly={merged.readonly}
      min={merged.min}
      max={merged.max}
      step={merged.step}
      value={merged.value}
      onInput={handleInput}
      onChange={handleChange}
    />
  );
}
