// src/renderer/Common/Header/Header.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface HeaderProps {
    bgColor?: string;
    children?: Snippet;
  }

  let { bgColor = "var(--bg-header)", children }: HeaderProps = $props();
</script>

<div
  style={`
    --bg-color: ${bgColor};
  `}
>
  {@render children?.()}
</div>

<style>
  div {
    display: flex;
    align-items: center;
    background-color: var(--bg-color);
  }
</style>

// src/renderer/shared/components/header/Header.tsx
import { ParentProps, mergeProps } from 'solid-js';
import styles from './Header.module.css';

interface HeaderProps extends ParentProps {
  bgColor?: string;
}

export function Header(props: HeaderProps) {
  const merged = mergeProps({ bgColor: 'var(--bg-header)' }, props);

  return (
    <div class={styles.header} style={{ '--bg-color': merged.bgColor }}>
      {props.children}
    </div>
  );
}
